name: ts-analysis

on: push

jobs:
  analysis:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node_setup
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: test_and_sonnar
        run: |
          cd src
          npm i -D typescript jest ts-jest @types/jest
          npm test
          node sonar-project.js $SONAR_TOKEN
