name: ts-analysis

on: push

jobs:
  analysis:
    runs-on: ubuntu-latest
    env:
      test: ${{ secrets.TEST }}

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: 
        - actions/checkout@v2
        - actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
      run: |
        cd src
        npm i -D typescript jest ts-jest @types/jest
        npm test
        echo "test: $test"
