name: ts-analysis

on: push

jobs:
  analysis:
    runs-on: ubuntu-latest
    env:
      test: ${{ secrets.TEST }}

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test_and_sonnar
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
        run: |
          cd src
          npm i -D typescript jest ts-jest @types/jest
          npm test
          echo "test: $test"
