name: ts-analysis

on:
  push:
    branches:
      - "*"

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: test_and_sonnar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd src
          npm i
          npm test
          node sonar-project.js $GITHUB_REF $SONAR_TOKEN
