name: ts-analysis

on: push

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: test_and_sonnar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd src
          npm i
          npm test
          node sonar-project.js $GITHUB_REF $SONAR_TOKEN
